#!/usr/bin/env python3
"""
Fully Automatic Quran Translation Converter
No user input required - detects everything automatically
Just run: python3 auto_convert.py
"""

import os
import sys
from datetime import datetime

# Quran structure: 114 surahs with ayah counts
QURAN_STRUCTURE = [
    7, 286, 200, 176, 120, 165, 206, 75, 129, 109,
    123, 111, 43, 52, 99, 128, 111, 110, 98, 135,
    112, 78, 118, 64, 77, 227, 93, 88, 69, 60,
    34, 30, 73, 54, 45, 83, 182, 88, 75, 85,
    54, 53, 89, 59, 37, 35, 38, 29, 18, 45,
    60, 49, 62, 55, 78, 96, 29, 22, 24, 13,
    14, 11, 11, 18, 12, 12, 30, 52, 52, 44,
    28, 28, 20, 56, 40, 31, 50, 40, 46, 42,
    29, 19, 36, 25, 22, 17, 19, 26, 30, 20,
    15, 21, 11, 8, 8, 19, 5, 8, 8, 11,
    11, 8, 3, 9, 5, 4, 7, 3, 6, 3,
    5, 4, 5, 6
]

def find_text_file():
    """Auto-detect text file in current directory"""
    current_dir = os.getcwd()
    
    # Priority order for file search
    priority_files = ['ahmed.txt', 'translation.txt', 'quran.txt']
    
    # First check priority files
    for filename in priority_files:
        filepath = os.path.join(current_dir, filename)
        if os.path.exists(filepath):
            return filepath, filename
    
    # Then check all .txt files
    for filename in os.listdir(current_dir):
        if filename.endswith('.txt'):
            filepath = os.path.join(current_dir, filename)
            return filepath, filename
    
    return None, None

def read_and_clean_lines(filepath):
    """Read file and return clean lines"""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        
        # Clean: remove empty lines and strip whitespace
        cleaned = [line.strip() for line in lines if line.strip()]
        return cleaned
    except Exception as e:
        print(f"❌ Error reading file: {e}")
        return None

def generate_sql(lines, translator='Ahmed Ali', language='en'):
    """Generate complete PostgreSQL SQL"""
    
    total_expected = sum(QURAN_STRUCTURE)
    
    if len(lines) != total_expected:
        print(f"⚠️  Warning: Expected {total_expected} ayahs, found {len(lines)} lines")
        if len(lines) < total_expected:
            print(f"❌ Error: Not enough lines in file!")
            return None
    
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    sql = f"""-- --------------------------------------------------------------------
-- Quran Translation: {translator}
-- Language: {language}
-- Generated: {timestamp}
-- Total Ayahs: {min(len(lines), total_expected)}
-- Auto-generated by auto_convert.py
-- --------------------------------------------------------------------

DROP TABLE IF EXISTS quran_translation;

CREATE TABLE quran_translation (
  id SERIAL PRIMARY KEY,
  sura INTEGER NOT NULL,
  aya INTEGER NOT NULL,
  text TEXT NOT NULL,
  translator VARCHAR(100) NOT NULL,
  language VARCHAR(10) DEFAULT 'en',
  added_by INTEGER REFERENCES users(id),
  is_approved BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_trans_sura_aya ON quran_translation(sura, aya);
CREATE INDEX idx_trans_translator ON quran_translation(translator);
CREATE INDEX idx_trans_language ON quran_translation(language);
CREATE UNIQUE INDEX idx_unique_translation ON quran_translation(sura, aya, translator);

"""
    
    # Map lines to Quran structure
    line_index = 0
    batch_size = 500
    current_batch = []
    batch_count = 0
    
    for surah_num, ayah_count in enumerate(QURAN_STRUCTURE, start=1):
        for ayah_num in range(1, ayah_count + 1):
            if line_index >= len(lines):
                break
            
            text = lines[line_index].replace("'", "''")
            current_batch.append((surah_num, ayah_num, text, translator, language))
            line_index += 1
            
            # Write batch when full
            if len(current_batch) >= batch_size:
                batch_count += 1
                sql += f"\n-- Batch {batch_count}\n"
                sql += "INSERT INTO quran_translation (sura, aya, text, translator, language) VALUES\n"
                
                for i, (s, a, t, tr, l) in enumerate(current_batch):
                    comma = "," if i < len(current_batch) - 1 else ";"
                    sql += f"({s}, {a}, '{t}', '{tr}', '{l}'){comma}\n"
                
                current_batch = []
        
        if line_index >= len(lines):
            break
    
    # Write remaining batch
    if current_batch:
        batch_count += 1
        sql += f"\n-- Batch {batch_count} (Final)\n"
        sql += "INSERT INTO quran_translation (sura, aya, text, translator, language) VALUES\n"
        
        for i, (s, a, t, tr, l) in enumerate(current_batch):
            comma = "," if i < len(current_batch) - 1 else ";"
            sql += f"({s}, {a}, '{t}', '{tr}', '{l}'){comma}\n"
    
    sql += "\n-- Conversion complete\n"
    
    return sql

def main():
    """Main execution"""
    print("=" * 70)
    print("  🤖 AUTOMATIC QURAN TRANSLATION CONVERTER")
    print("=" * 70)
    print()
    
    # Step 1: Find text file
    print("🔍 Searching for text file...")
    filepath, filename = find_text_file()
    
    if not filepath:
        print("❌ No .txt file found in current directory!")
        print("   Please ensure ahmed.txt or translation.txt exists here.")
        sys.exit(1)
    
    print(f"✅ Found: {filename}")
    print()
    
    # Step 2: Read file
    print("📂 Reading file...")
    lines = read_and_clean_lines(filepath)
    
    if not lines:
        print("❌ Failed to read file or file is empty")
        sys.exit(1)
    
    print(f"✅ Read {len(lines)} lines")
    print()
    
    # Step 3: Generate SQL
    print("🔄 Converting to PostgreSQL format...")
    
    # Auto-detect translator from filename
    translator = 'Ahmed Ali'  # Default
    if 'ahmed' in filename.lower():
        translator = 'Ahmed Ali'
    elif 'sahih' in filename.lower():
        translator = 'Sahih International'
    elif 'pickthall' in filename.lower():
        translator = 'Pickthall'
    
    sql_content = generate_sql(lines, translator, 'en')
    
    if not sql_content:
        print("❌ Failed to generate SQL")
        sys.exit(1)
    
    print(f"✅ SQL generated successfully")
    print()
    
    # Step 4: Auto-generate output filename
    output_file = 'quran_translation.sql'
    
    print(f"💾 Writing to: {output_file}")
    
    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(sql_content)
    except Exception as e:
        print(f"❌ Error writing file: {e}")
        sys.exit(1)
    
    print()
    print("=" * 70)
    print("  ✅ SUCCESS!")
    print("=" * 70)
    print()
    print("📊 Summary:")
    print(f"   Input:       {filename}")
    print(f"   Output:      {output_file}")
    print(f"   Translator:  {translator}")
    print(f"   Lines:       {len(lines)}")
    print()
    print("🚀 Next Steps:")
    print(f"   docker cp {output_file} quran-app-db-dev:/tmp/")
    print(f"   docker exec -it quran-app-db-dev psql -U myapp_user -d myapp_db -f /tmp/{output_file}")
    print()
    print("✅ Script completed successfully!")
    print()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
